name: Push to ECR

on:
  pull_request:
    branches:    
      - main
    paths:
      - container/accounts/test/**
  # pull_request_review:
  #   types: [submitted]

jobs:
  check_mergeable:
    runs-on: ubuntu-latest
    steps:  
      - name: Check PR state
        env: 
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR mergeable status
          PR_MERGEABLE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
              | jq -r '.mergeable')

          if [[ "$PR_MERGEABLE" == "false" ]]; then
            echo "PR is not mergeable."
            exit 1
          else
            echo "PR is mergeable."
          fi

  build:
    needs: 
      - check_mergeable
    timeout-minutes: 15
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo execute!
