name: Push to ECR

on:
  pull_request:
    branches:    
      - main
    paths:
      - container/accounts/test/**
  # pull_request_review:
  #   types: [submitted]

jobs:
  check_mergeable:
    runs-on: ubuntu-latest
    steps:  
      - name: dump context
        run: echo '${{ toJSON(github) }}'
      - name: Check PR Mergeable
        id: check_pr
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            console.log(pr);
            if (pr.mergeable === 'clean' || pr.mergeable === 'has_hooks') {
              console.log("PR is mergeable");
              return "true";
            } else {
              console.log("PR is not mergeable");
              return "false";
            }
      # - name: Get result
      #   run: |
      # - name: Check Mergeable
      #   run: |
      #     PR_NUMBER=${{ github.event.pull_request.number }}
      #     GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub Actions

      #     # Get PR mergeable status
      #     PR_MERGEABLE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
      #         "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
      #         | jq -r '.mergeable')

      #     if [[ "$PR_MERGEABLE" == "false" ]]; then
      #       echo "PR is not mergeable."
      #       exit 1
      #     else
      #       echo "PR is mergeable."
      #     fi
# echo "${{steps.check_pr.outputs.result}}"
      - name: Check PR state
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Get PR mergeable status
          PR_MERGEABLE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
              | jq -r '.mergeable')

          if [[ "$PR_MERGEABLE" == "false" ]]; then
            echo "PR is not mergeable."
            exit 1
          else
            echo "PR is mergeable."
          fi
    outputs:
      pr_state: ${{steps.check_pr.outputs.result}}

  build:
    needs: 
      - check_mergeable
    timeout-minutes: 15
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{needs.check_mergeable.outputs.pr_state}}
