name: Push to ECR

on:
  pull_request:
    branches:    
      - main
    paths:
      - container/accounts/test/**
  # pull_request_review:
  #   types: [submitted]

jobs:
  check_mergeable:
    runs-on: ubuntu-latest
    steps:  
      - name: Check PR state
        env: 
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR mergeable status
          PR_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
          
          PR_MERGEABLE=$(echo "$PR_JSON" | jq -r '.mergeable')
          PR_MERGEABLE_STATE=$(echo "$PR_JSON" | jq -r '.mergeable_state')
          
          if [[ "$PR_MERGEABLE" != "true" ]] || [[ "$PR_MERGEABLE_STATE" == "blocked" ]]; then
            echo "PR is not mergeable. mergeable: $PR_MERGEABLE, mergeable_state: $PR_MERGEABLE_STATE"
            exit 1
          else
            echo "PR is mergeable. mergeable: $PR_MERGEABLE, mergeable_state: $PR_MERGEABLE_STATE"
          fi

  build:
    needs: 
      - check_mergeable
    timeout-minutes: 15
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo execute!
